version: '3.7'

services:
  frontend:
    container_name: judge_frontend
    build:
      context: ./frontend
    restart: always

  backend:
    container_name: judge_backend
    build:
      context: ./backend
      args:
        - DJANGO_ENV=production
    restart: always
    env_file:
      - ./backend/config/.env
    volumes:
      - media-files:/backend/src/media
      - static-files:/backend/src/static
    depends_on:
      - database
      - redis
    stdin_open: true
    tty: true

  redis:
    container_name: judge_redis
    image: redis:4
    restart: always

  celery:
    container_name: judge_celery
    build:
      context: ./backend
      args:
        - DJANGO_ENV=production
    entrypoint: bash -c "cd src; celery -A judge worker -l info"
    env_file:
      - ./backend/config/.env
    volumes:
      - media-files:/backend/src/media
    depends_on:
      - database
      - redis

  database:
    image: postgres:11.1
    container_name: judge_db
    env_file:
      - ./backend/config/.env
    restart: always

  nginx:
    container_name: judge_nginx
    restart: always
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: nginx.conf
    depends_on:
      - backend
    ports:
      - 8001:80
    volumes:
      - media-files:/media
      - static-files:/static

volumes:
  media-files:
  static-files:
