version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      args:
        - DJANGO_ENV=production
    restart: unless-stopped
    env_file:
      - ./backend/config/.env
    volumes:
      - ./backend:/backend
      - media-files:/backend/src/media
      - static-files:/backend/src/static
    depends_on:
      - database
      - redis

  redis:
    container_name: judge_redis
    image: redis:4
    restart: always

  celery:
    build:
      context: ./backend
      args:
        - DJANGO_ENV=development
    entrypoint: bash -c "cd src; celery -A judge worker -l info"
    env_file:
      - ./backend/config/.env
    volumes:
      - ./backend:/backend
      - media-files:/backend/src/media
    depends_on:
      - database
      - redis

  database:
    image: postgres:11.1
    container_name: judge_db
    env_file:
      - ./backend/config/.env
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: nginx.dev.conf
    depends_on:
      - backend
    ports:
      - 8001:80
    volumes:
      - media-files:/media
      - static-files:/static

volumes:
  media-files:
  static-files:
