version: '3.7'

services:
  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
    ports:
      - 3000:3000

  backend:
    build:
      args:
        - DJANGO_ENV=development
    env_file:
      - ./backend/config/.env.dev
    volumes:
      - ./backend:/backend
      - media-files:/backend/src/media
      - static-files:/backend/src/static
    depends_on:
      - database
      - redis
    restart: unless-stopped

  redis:
    restart: unless-stopped

  celery:
    build:
      context: ./backend
      args:
        - DJANGO_ENV=development
    entrypoint: bash -c "cd src; celery -A judge worker -l info"
    env_file:
      - ./backend/config/.env.dev
    volumes:
      - ./backend:/backend
      - media-files:/backend/src/media
    depends_on:
      - database
      - redis

  database:
    image: postgres:11.1
    container_name: judge_db
    env_file:
      - ./backend/config/.env
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: nginx.conf
    depends_on:
      - backend
    ports:
      - 8001:80
    volumes:
      - media-files:/media
      - static-files:/static
    restart: unless-stopped

volumes:
  media-files:
  static-files:
