# Generated by Django 2.2.6 on 2019-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_judgesubmissionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WAITING_FOR_REVIEW', 'Waiting for review'), ('INVALID_FORMAT', 'Invalid format')], max_length=18),
        ),
    ]
