# Generated by Django 2.2.6 on 2020-11-12 11:09

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20191025_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='answers_csv',
            field=models.FileField(null=True, upload_to=competition.models.answers_csv_directory_path),
        ),
    ]
