# Generated by Django 2.2.6 on 2020-11-14 11:07

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20201113_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='answers_csv',
            field=models.FileField(blank=True, null=True, upload_to=competition.models.answers_csv_directory_path),
        ),
    ]
