# Generated by Django 2.2.6 on 2020-11-14 12:02

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20201114_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=competition.models.csv_directory_path),
        ),
    ]
