# Generated by Django 2.2.6 on 2019-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
